"""
note_cleaning.py -- deterministic boilerplate stripper for clinical notes (NO LLM).

Instead of extracting only the A&P (text_sections.extract_excerpt), this KEEPS the
full clinical narrative and REMOVES known low-value boilerplate sections (Review of
Systems, Physical Exam, Labs, Medications, Family/Social/Past-Medical History,
Allergies, performance-status scales, consent, palliative symptom scales) plus
copy-paste footer/signature blocks.

The Past Surgical History (PSH) block is copy-pasted VERBATIM across a patient's
notes (an EHR-autogenerated cumulative list, like the Cancer Treatment History), so
it is pulled OUT to a separate field to be de-duplicated to ONE canonical copy per
patient rather than repeated in every note. NOTE: this release extracts the PSH block
(strip_boilerplate -> psh_block) but ships no downstream consumer for it; the per-patient
dedup stage is not included.

Design (robust to inconsistent EHR formatting):
  1. normalize   -- CRLF->LF, tabs->space, runs of 2+ spaces -> newline
  2. segment     -- split at EVERY recognized header (KEEP | REMOVE | PSH registry)
  3. classify    -- drop REMOVE; keep KEEP + UNKNOWN (conservative); PSH -> own field
  4. struct wipe -- remove residual lab / vitals / ROS-PE body-system / med lines
  5. footer wipe -- remove signature / address / dictation footer lines
  6. empty check -- < MIN_KEEP_CHARS remaining -> flag stripped_empty

Everything is deterministic, dependency-free, and unit-testable without Spark.
"""
import re
from typing import Dict, List, Optional, Tuple

MIN_KEEP_CHARS = 200

# ---------------------------------------------------------------------------
# 1. HEADER REGISTRIES  (lower-case; matched at a word/section boundary)
# ---------------------------------------------------------------------------
# KEEP: the clinical narrative that carries line-of-therapy signal.
KEEP_HEADERS: List[str] = [
    "chief complaint / reason for visit", "chief complaint", "reason for visit",
    "reason for consultation", "reason for assessment", "reason for referral",
    "history of present illness", "subjective history of present illness",
    "hpi", "interval history", "interim history", "subjective",
    "diagnosis", "diagnoses", "staging", "pathology", "molecular",
    "labs/imaging/pathology",
    # active/current regimen -- unique-per-visit LoT signal, KEEP (not cumulative CTH)
    "current cancer treatment", "current treatment",
    # TX-Surgery / TX-Other therapies: KEEP inline in the excerpt (per request) rather than
    # pulling to a CTH block (those columns are removed).
    "tx-surgery", "tx-other therapies",
    "impression and recommendations", "impression", "recommendations", "recommendation",
    "assessment and plan", "assessment & plan", "assessment/plan", "a&p", "a/p",
    "discussion and plan", "immediate clinical problem lists/plans",
    "immediate clinical problem", "assessment", "plan of care", "plan of action",
    "treatment plan", "plans", "plan",
    # inline imaging findings (KEEP per clinical decision - used for cPD corroboration)
    "diagnostic imaging", "imaging review", "imaging", "examination",
    "imaging interpretation", "radiologic interpretation", "ct interpretation",
    "mri interpretation",
    # Op Note -- procedure title + clinical context (carries LoT: HIPEC drug/dose etc.)
    "title of operation", "procedures performed", "procedure",
    "indications for surgery", "indications for the procedure", "indications",
    # Op Note -- disease burden / CRS outcome
    "operative findings", "findings",
    "peritoneal carcinomatosis index", "completeness of cytoreduction",
    "pre-operative diagnosis", "preoperative diagnosis",
    "post-op diagnosis", "postoperative diagnosis",
]

# CTH: cumulative Cancer Treatment History -- copy-pasted across notes (growing numbered
# list). Extracted ONCE per patient (most complete version) and pre-loaded in Stage 3.
# Must be REMOVED from individual note bodies to avoid massive token waste on duplicates.
CTH_HEADERS: List[str] = [
    "oncology history overview note", "oncology history overview",
    "oncologic history", "oncology history",
    "prior cancer treatment", "cancer treatment history",
    "prior treatment", "treatment history",
    "chemotherapy summary",
]

# Each CTH header maps to a canonical SECTION key -> its own column in enlist_notes_prepped.
# (Multiple synonymous headers collapse to one section; unmapped CTH headers -> treatment_history.)
# Note: TX-Chemotherapy / TX-Radiation are no longer extracted (were always null); TX-Surgery /
# TX-Other therapies are now KEEP (kept inline in the excerpt), not CTH sections.
CTH_SECTION_KEYS: List[str] = [
    "oncologic_history", "treatment_history", "chemotherapy_summary",
]
_CTH_SECTION: Dict[str, str] = {
    "oncology history overview note": "oncologic_history",
    "oncology history overview": "oncologic_history",
    "oncologic history": "oncologic_history",
    "oncology history": "oncologic_history",
    "prior cancer treatment": "treatment_history",
    "cancer treatment history": "treatment_history",
    "prior treatment": "treatment_history",
    "treatment history": "treatment_history",
    "chemotherapy summary": "chemotherapy_summary",
}

# REMOVE: boilerplate with no line-of-therapy value.
REMOVE_HEADERS: List[str] = [
    # Review of systems
    "review of systems", "review of system", "12-point review of systems", "ros",
    # Physical exam + objective + vitals
    "physical examination", "physical exam", "objective physical exam", "objective",
    "vital signs", "visit vitals", "vitals", "general appearance",
    # Labs / data review
    "laboratory studies", "laboratory data", "laboratory review", "laboratory",
    "pertinent labs", "recent results", "data review", "lab data", "labs",
    # Medications
    "current outpatient prescriptions", "current outpatient medications",
    "current inpatient pain medications", "current facility-administered medications",
    "anticoagulation / antiplatelet medications", "medication review",
    "current medications", "new prescriptions", "discontinued medications",
    "previous medications", "modified medications", "medications",
    # Prior-to-admission / home / admission med lists (Epic autogenerated tables that leak
    # into adjacent sections, e.g. the tail of a Chemotherapy summary block).
    "prior to admission meds", "prior to admission medications",
    "medications prior to admission", "home medications",
    "admission medications", "medications on admission",
    # Histories (non-oncologic)
    "past medical history", "past surgical history",  # PSH re-classified below
    "patient active problem list", "active problem list",
    "socioeconomic history", "occupational history", "social history narrative",
    "substance use topics", "substance use", "tobacco use", "family history",
    "social history", "habits",
    # Allergies
    "no known allergies", "allergies",
    # Performance status / consent / education
    "ecog performance status", "karnofsky", "ecog",
    "anesthesia consent", "consent", "patient education", "patient instructions",
    "referrals / consults", "referrals", "asa classification",
    # Palliative / psych scales
    "edmonton symptom assessment", "edmonton classification", "esas",
    "cage-aid", "mdas", "medd", "psychosocial and spiritual", "advanced directives",
    "mental status exam", "ecs-cp", "bowel movement",
    # Op Note -- surgical narrative (5-12K chars of noise: sutures, staplers, dissection)
    "details of the procedure", "procedure in detail", "description of procedure",
    "operative technique", "technique",
    # Op Note -- admin / logistics
    "anesthesia", "estimated blood loss", "complications",
    "specimens sent", "specimens removed", "specimens",
    "drains placed", "operating time",
    "i's and o's", "intraprocedure i/o totals",
    # Op Note -- specimen table (contains "INTERPRETATION" on every line -- not imaging)
    "pathology surgical specimen interpretation", "pathology surgical specimen",
]

# PSH: kept ONCE per patient (extracted, then removed from the note body).
PSH_HEADERS: List[str] = ["past surgical history", "surgical history"]

_CATEGORY: Dict[str, str] = {}
for _h in KEEP_HEADERS:
    _CATEGORY.setdefault(_h, "keep")
for _h in CTH_HEADERS:
    _CATEGORY.setdefault(_h, "cth")
for _h in REMOVE_HEADERS:
    _CATEGORY.setdefault(_h, "remove")
for _h in PSH_HEADERS:
    _CATEGORY[_h] = "psh"          # PSH wins over the REMOVE entry for "past surgical history"

_ALL_HEADERS = sorted(set(list(_CATEGORY.keys())), key=len, reverse=True)


# ---------------------------------------------------------------------------
# 2. STRUCTURAL / FOOTER LINE PATTERNS  (fallback for header-less noise)
# ---------------------------------------------------------------------------
# Lab value line: "WBC 6.1 4.0-11.0 K/uL" / "Sodium Lvl 139 (L) 136-145 mEq/L"
_LAB_LINE = re.compile(
    r"^[A-Za-z][\w \-/%().,]{0,34}\s+-?\d+\.?\d*\s*\(?[HL]?\)?\s*"
    r"(\d+\.?\d*\s*-\s*\d+\.?\d*)?\s*"
    r"(mg/dl|meq/l|k/ul|u/l|g/dl|gm/dl|ng/ml|mmol/l|mm/hr|%|iu/l|pg|fl|/ul|cells)",
    re.IGNORECASE,
)
# Vitals: "BP 120/72 | Pulse 93 | Temp 36.6" / "T: 98.6 P: 88 BP: 120/70"
_VITALS = re.compile(
    r"(?i)\b(bp|blood pressure)\b\s*:?\s*\d{2,3}\s*/\s*\d{2,3}.*(pulse|puls|hr|temp|resp|spo2|weight|bmi|\bo2\b)",
)
# ROS / PE body-system finding line: "Cardiovascular: Regular rate and rhythm, no murmurs"
_BODYSYS = re.compile(
    r"(?i)^(constitutional|general|heent|hent|head|eyes|ears|nose|throat|neck|"
    r"respiratory|lungs|chest|cardiovascular|heart|gastrointestinal|abdomen|abdominal|"
    r"endocrine|genitourinary|musculoskeletal|extremities|lymphatic|lymph|skin|"
    r"integumentary|neurologic(al)?|hematologic(al)?|psychiatric(/behavioral)?|"
    r"allergic/immunologic|immunologic|breasts?|back|pulmonary|vascular)\s*:\s*\S",
)
_BODYSYS_EXAM_VOCAB = re.compile(
    r"(?i)(negative|normal|wnl|no acute|unremarkable|intact|nontender|non-tender|"
    r"no murmur|regular rate|no edema|nad\b|well[- ]?developed|no distress|denies|"
    r"clear to ausc|soft,|benign|alert and oriented|no rash|no cyanosis|no clubbing|"
    r"grossly|symmetric|supple|no lym |no palpable|deferred|not examined)"
)
# Footer / signature / address / dictation lines.
_FOOTER = re.compile(
    r"(?i)(electronically signed( by)?|dictated by|dictated:|transcribed( by)?:?|"
    r"authenticated by|signed by|completed by|cosigned by|co-signed by|"
    r"document status|encounter date:|date/time:|job #|job#|"
    r"\bfax\b|phone:|tel:|suite \d+|"
    r"\b\d{3,5}\s+[nsew]?\.?\s?[a-z ]+ (street|st|avenue|ave|blvd|drive|dr|road|rd|"
    r"boulevard|suite|lane|ln)\b|"
    r"houston,?\s*(tx|texas)|,\s*(tx|texas)\s*7\d{4}|\b7\d{4}\b)"
)
_MED_LINE = re.compile(
    r"(?i)(^\s*[•\-\*]|\btake\b|\binject\b|\d+\s*(mg|mcg|units?|ml)\b).{0,80}"
    r"(by mouth|orally|p\.o\.|\bpo\b|tablet|capsule|injection|daily|twice daily|"
    r"once daily|every \d+ hours|as needed|q\d+h|bid|tid|qid|prn|subcutaneous)"
)

# Inline (flattened, single-spaced) lab-table noise -- removed regardless of line
# breaks or which section it sits under (some notes mislabel labs as "Pathology:").
_LAB_UNIT = r"(?:mg/dl|meq/l|k/ul|u/l|g/dl|gm/dl|ng/ml|mmol/l|iu/l|mm/hr|pg|fl|/ul|%)"
_LAB_COL_HDR = re.compile(r"(?i)date\s*/\s*time\s+value\s+ref\s+range\s+status")
_LAB_COMMENT = re.compile(
    r"(?i)comment:\s*note:[^.]*?effective\s+\d{1,2}/\d{1,2}/\d{4}\s+at\s+\d{3,4}"
)
# One analyte reading: "MM/DD/YYYY HH:MM AM 4.7 (L) 4.0 - 11.0 K/uL Final"
_LAB_READING = re.compile(
    r"(?i)\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}\s*[ap]m\s+-?\d+\.?\d*\s*\(?[hl]?\)?\s*"
    r"(?:<=|>=)?\s*[\d.\s\-]*?" + _LAB_UNIT + r"\s*(?:final|prelim)?"
)
_LAB_LEADIN = re.compile(r"(?i)i have reviewed laboratory results\.?")
_LAB_REFRANGE = re.compile(r"(?i)reference ranges:\s*smoker:[\d.\s\-]*")
_LAB_NORESULTS = re.compile(r"(?i)no results found\.?")


def _strip_inline_labs(text: str) -> str:
    """Remove flattened lab-table debris (methodology comments, per-analyte readings,
    column headers, lead-ins) that the line-level filter cannot isolate on a single line.
    Narrative values (e.g. 'CEA rose to 52.6') are safe: they lack the
    date->value->unit->Final reading structure this targets."""
    text = _LAB_COMMENT.sub(" ", text)
    text = _LAB_READING.sub(" ", text)
    text = _LAB_COL_HDR.sub(" ", text)
    text = _LAB_LEADIN.sub(" ", text)
    text = _LAB_REFRANGE.sub(" ", text)
    text = _LAB_NORESULTS.sub(" ", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text


# ---------------------------------------------------------------------------
# 3. CORE HELPERS
# ---------------------------------------------------------------------------
def _normalize(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\t", " ")
    text = re.sub(r"[ \u00a0]{2,}", "\n", text)   # 2+ spaces (incl. nbsp) => section break
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def _is_boundary(hay: str, idx: int) -> bool:
    """True if the char before idx is a non-alphanumeric (section/word boundary)."""
    if idx == 0:
        return True
    return not hay[idx - 1].isalnum()


def _find_all_headers(hay: str) -> List[Tuple[int, str, str]]:
    """All boundary-anchored header hits: list of (pos, header, category), de-overlapped."""
    hits: List[Tuple[int, str, str]] = []
    for h in _ALL_HEADERS:
        start = 0
        while True:
            j = hay.find(h, start)
            if j < 0:
                break
            if _is_boundary(hay, j) and _looks_like_header(hay, j, h):
                hits.append((j, h, _CATEGORY[h]))
            start = j + 1
    hits.sort(key=lambda t: (t[0], -len(t[1])))
    # de-overlap: keep the first (longest at a position), drop any hit starting inside it
    deduped: List[Tuple[int, str, str]] = []
    last_end = -1
    for pos, h, cat in hits:
        if pos >= last_end:
            deduped.append((pos, h, cat))
            last_end = pos + len(h)
    return deduped


def _looks_like_header(hay: str, j: int, h: str) -> bool:
    """Guard against mid-sentence false positives. A real section header is TERMINATED by a
    colon or a newline (or end-of-text) -- e.g. 'CANCER TREATMENT HISTORY:' or a standalone
    header line. We do NOT blanket-trust multiword headers, because header PHRASES also occur
    inside running prose (e.g. 'intra-operative findings included ...' inside a treatment-
    history narrative) and must NOT split the block.

    Also reject a match whose PRECEDING char is a hyphen or alphanumeric (e.g. the 'operative
    findings' inside 'intra-operative findings' is part of a larger word)."""
    # preceding char guard: hyphen-joined or alnum-joined => part of a larger token
    if j > 0 and (hay[j - 1] == "-" or hay[j - 1].isalnum()):
        return False
    after = j + len(h)
    if after >= len(hay):
        return True                      # header at very end of text
    tail = hay[after:after + 3]
    if tail[:1] in (":", "\n"):
        return True
    if tail.strip()[:1] == ":":          # header followed by a couple spaces then ':'
        return True
    return False


def _strip_structural(segment: str) -> str:
    """Line-level removal of residual lab / vitals / body-system exam / med / footer lines."""
    out: List[str] = []
    for line in segment.split("\n"):
        s = line.strip()
        if not s:
            continue
        # Footer: signatures, addresses — always short. Long lines that happen to mention a
        # city (e.g. an HPI naming the patient's home town) must NOT be killed.
        if _FOOTER.search(s) and len(s) < 300:
            continue
        if _LAB_LINE.match(s):
            continue
        if _VITALS.search(s) and len(s) < 300:
            continue
        if _MED_LINE.search(s) and len(s) < 120:
            continue
        if _BODYSYS.match(s) and (_BODYSYS_EXAM_VOCAB.search(s) or len(s) < 120):
            continue
        out.append(s)
    return "\n".join(out).strip()


def dedupe_cth_paragraphs(blocks: List[Tuple[Optional[str], Optional[str]]]) -> Optional[str]:
    """Consolidate one CTH section for a patient by BLANK-LINE PARAGRAPH exact-dedup.

    Pools a patient's per-note snapshots of ONE CTH section, splits each snapshot into
    paragraph blocks on blank lines, and keeps only DISTINCT paragraphs (exact match after
    whitespace/case normalization), in first-appearance (oldest-first) order. Verbatim repeats
    of the same paragraph across many notes collapse to a single copy; paragraphs that differ
    at all (e.g. drifting 'X of Y cycles' counts) are each kept.

    blocks: list of (text, sort_key) -- sort_key is typically the note date (sortable string).
    """
    seen = set()
    out: List[str] = []
    for text, _ in sorted(blocks, key=lambda b: (b[1] is None, b[1] or "")):
        if not text or not str(text).strip():
            continue
        for para in re.split(r"\n\s*\n", str(text)):     # split on blank lines
            p = para.strip()
            if not p:
                continue
            # Drop a leaked trailing section header (e.g. 'Subjective' from the next note
            # section) so paragraphs that are identical except for that suffix collapse to one.
            p = re.sub(r"\s*\bsubjective\b\s*$", "", p, flags=re.IGNORECASE).strip()
            if not p:
                continue
            key = re.sub(r"\s+", " ", p).strip().lower()  # normalize for exact compare
            if key not in seen:
                seen.add(key)
                out.append(p)
    return ("\n\n".join(out).strip() or None) if out else None


# ---------------------------------------------------------------------------
# 3c. RESEARCH-COORDINATOR "Study Interim" pre-clean
# ---------------------------------------------------------------------------
# These trial-visit notes (authoring_provider_type = "Research Coordinator",
# note_type = "Study Interim") carry a large low-value span: a Questionnaires blurb,
# an Adverse-Events table, and a concomitant-medications list -- then a high-value
# "Additional Notes" section (response assessment + treatment decision). Remove the
# span from the Questionnaires header up to the first Notes/Assessment section.
_RC_QUESTIONNAIRE = re.compile(r"(?i)questionnair+es?\s*:")          # questionnaires / questionnairres
_RC_END_BOUNDARY = re.compile(
    r"(?i)\b(additional\s+notes|notes|assessment(?:\s*(?:and|/)\s*plan)?)\s*:"
)


def strip_research_coordinator_questionnaires(text: Optional[str]) -> Optional[str]:
    """Remove the Questionnaires -> (AE table + meds) span from a Research-Coordinator
    Study-Interim note, up to the first 'Additional Notes:' / 'Notes:' / 'Assessment...:'
    boundary. If no such boundary exists after the questionnaire header, remove to end of
    note (only AE/meds boilerplate follows). No-op if there is no questionnaire header."""
    if not text:
        return text
    m = _RC_QUESTIONNAIRE.search(text)
    if not m:
        return text
    q_start = m.start()
    b = _RC_END_BOUNDARY.search(text, m.end())
    if b:
        return text[:q_start].rstrip() + "\n" + text[b.start():]
    return text[:q_start].rstrip()


# ---------------------------------------------------------------------------
# 4. PUBLIC API
# ---------------------------------------------------------------------------
def strip_boilerplate(note_text: Optional[str]) -> Dict[str, object]:
    """
    Return a diagnostics dict:
      cleaned_note      : the note with boilerplate removed (or None if empty/blank)
      psh_block         : the Past Surgical History block (or None)
      cth_block         : the full Cancer Treatment History block (all CTH sections joined; or None)
      cth_sections      : dict {section_key: text or None} split by CTH header
                          (keys = CTH_SECTION_KEYS: oncologic_history, treatment_history,
                          chemotherapy_summary)
      removed_headers   : list of REMOVE/PSH/CTH headers found and dropped
      kept_headers      : list of KEEP headers retained
      original_length   : len(note_text)
      cleaned_length    : len(cleaned_note or "")
      flagged_empty     : True if < MIN_KEEP_CHARS survived
    """
    result = {
        "cleaned_note": None, "psh_block": None, "cth_block": None,
        "cth_sections": {k: None for k in CTH_SECTION_KEYS},
        "removed_headers": [], "kept_headers": [],
        "original_length": 0, "cleaned_length": 0,
        "flagged_empty": True,
    }
    if not note_text or not str(note_text).strip():
        return result

    original = str(note_text)
    result["original_length"] = len(original)
    text = _normalize(original)
    hay = text.lower()

    hits = _find_all_headers(hay)

    removed: List[str] = []
    kept: List[str] = []
    psh_parts: List[str] = []
    cth_parts: List[str] = []
    cth_by_section: Dict[str, List[str]] = {}
    keep_parts: List[str] = []

    if not hits:
        # No recognized structure -> keep whole note (conservative), still strip lines/footer.
        cleaned = _strip_structural(_strip_inline_labs(text))
    else:
        prologue = text[: hits[0][0]].strip()
        if prologue:
            keep_parts.append(prologue)
        for i, (pos, h, cat) in enumerate(hits):
            end = hits[i + 1][0] if i + 1 < len(hits) else len(text)
            segment = text[pos:end].strip()
            if not segment:
                continue
            if cat == "remove":
                removed.append(h)
            elif cat == "psh":
                removed.append(h)
                psh_parts.append(segment)
            elif cat == "cth":
                removed.append(h)
                cth_parts.append(segment)
                sec = _CTH_SECTION.get(h, "treatment_history")
                cth_by_section.setdefault(sec, []).append(segment)
            else:  # keep
                kept.append(h)
                keep_parts.append(segment)
        cleaned = _strip_structural(_strip_inline_labs("\n\n".join(keep_parts)))

    result["removed_headers"] = removed
    result["kept_headers"] = kept
    result["psh_block"] = ("\n\n".join(psh_parts).strip() or None) if psh_parts else None
    result["cth_block"] = ("\n\n".join(cth_parts).strip() or None) if cth_parts else None
    result["cth_sections"] = {
        k: ("\n\n".join(cth_by_section[k]).strip() or None) if cth_by_section.get(k) else None
        for k in CTH_SECTION_KEYS
    }

    cleaned = (cleaned or "").strip()
    result["cleaned_length"] = len(cleaned)
    if len(cleaned) >= MIN_KEEP_CHARS:
        result["cleaned_note"] = cleaned
        result["flagged_empty"] = False
    else:
        # Too little survived: keep what we have but flag it (agent index can exclude).
        result["cleaned_note"] = cleaned or None
        result["flagged_empty"] = True
    return result
